### ISSUE TITLE
Module not found: Error: Can't resolve 'history' in '/home/node/app/src'

### ISSUE THREAD

**Issue by NumanTeleprompter** [zoom/zoomapps-advancedsample-react#17]
Keep getting an error from frontend/src/index.js and an issue with:

import { createHashHistory } from "history";

have tried npm installing history again & @types/history

![image](https://github.com/user-attachments/assets/e518a0a8-82a8-4c3a-b1be-10998d35dd4f)
![image](https://github.com/user-attachments/assets/b6cbf4be-0151-4b43-ad76-f29542eb5776)

**Comment by StoneWolf** [comment]
Did you upgrade react router? If so, you also need to migrate its code to v6: https://reactrouter.com/en/main/upgrading/v5.

**Comment by RealmX1** [comment]
with v6 on frontend and v5 on back end it result in another issue. I came here looking for solution to that issue and saw the reply, and tried downgrading front end react router to v5, and recreated the above mentioned issue.

**Comment by RealmX1** [comment]
I was having the same issue

Thanks @StoneWolf . Reverting to v5 by running the following in "exec" section of frontend container
```bash
npm uninstall react-router-dom
npm install react-router-dom@5
```
Does seem to fix this part of the problem.

An actual fix for the code base would require changing package-lock.json and package.json for front end to use v5 for react router
