### ISSUE TITLE
From zoom client it's sending 304 from backend instead of redirection

### ISSUE THREAD

**Issue by aaditya6895** [zoom/zoomapps-advancedsample-react#2]
I cloned this branch and did all the things as described in readme file
but when I am trying to install the app nothing is opening into the app inside zoom client and in the backend logs it's showing 304
with the same URL I am trying in browser it's responding with 200 but we can't use that sdk in external browser

**Comment by SafeeSaif** [comment]
Potentially an ngrok free trial version. Refer to [https://github.com/zoom/zoomapps-sample-js/issues/1](this)
