### ISSUE TITLE
installing new packages fails to compile

### ISSUE THREAD

**Issue by TCashion** [zoom/zoomapps-advancedsample-react#7]
Hello, 

I'm using this sample app and am having some trouble with installing new packages. For example if I

* install in the frontend directory `npm install @zoom/appssdk` (just using zoomSdk as an example here, I understand it's already imported in index.html)
* import the package into a React component file with `import zoomSdk from "@zoom/appssdk"`
* then go through the steps to install the app in Zoom
 
I get this error: 

```
Cannot find module '@zoom/appssdk'
webpackMissingModule@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:21:59
./src/App.js@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:21:143
@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:49017:35
__webpack_require__@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:48453:37
fn@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:48674:28
./src/index.js@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:1600:81
@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:49017:35
__webpack_require__@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:48453:37
@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:49663:56
global code@https://1478-71-218-251-54.ngrok-free.app/api/zoomapp/proxy/static/js/bundle.js:49665:12
```

This seems to be an issue with the default webpack configuration for the project, but just wondering if anyone has gotten around this before?

**Comment by bmcminn** [comment]
Your logs specify it's attempting to load from https://1478-71-218-251-54.ngrok-free.app, is your ngrok instance running when you attempt `npm install @zoom/appssdk`? and if so, you may need to update the ngrok instance ID in the `PUBLIC_URL` `.env` variable which is one of my least favorite parts about using ngrok's free teir.

Additionally, the appssdk is distrubuted via Zoom CDN, https://appssdk.zoom.us/ so if needed you could download it into a `/lib/zoom-appssdk` directory and reference it that way.

**Comment by TCashion** [comment]
I cleared out all my docker images and rebuilt and was able to get some other installed packages to work... for Zoom I'll just stick with the current import for now. I'll close this out.
